# Generated by Django 4.2.23 on 2025-09-01 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('bio', models.TextField(blank=True)),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('availability_notes', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=80)),
                ('pet_name', models.CharField(max_length=80)),
                ('service_type', models.CharField(choices=[('walk', 'Walking'), ('care', 'Pet Care')], max_length=10)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sitter')),
            ],
        ),
    ]
